#pragma once
#include <string_view>

namespace LanguageData {
    inline constexpr std::string_view languageJson = R"(﻿{
  "EN": {
    "MODULE_ABOUT": "About",
    "MODULE_PLAYER": "Player",
    "MODULE_WORLD": "World",
    "MODULE_VISUALS": "Visuals",
    "MODULE_ESP": "ESP",
    "MODULE_MISC": "MISC",
    "MODULE_SETTINGS": "Settings",
    "About": "About",
    "Player": "Player",
    "World": "World",
    "Visuals": "Visuals",
    "ESP": "ESP",
    "MISC": "MISC",
    "Settings": "Settings",
    "Author": "Author:",
    "EchoTeam": "EchoTeam",
    "WWEcho is developing": "WWEcho is developing",
    "SETTINGS_LANGUAGE": "Setting Language",
    "SETTINGS_GENERAL": "Setting General",
    "MENU_HOTKEY_TITLE": "Show Menu",
    "CONSOLE_HOTKEY_TITLE": "Show console",
    "CONSOLE_HOTKEY_DESC": "Show/Hide console log window.",
    "SHOW_STATUS_WINDOW_TITLE": "Show status window",
    "SHOW_STATUS_WINDOW_DESC": "Shows a window with statements of enabled functions.",
    "MOVE_STATUS_TITLE": "Move status window",
    "SHOW_FPS_TITLE": "Show current FPS",
    "SHOW_FPS_DESCRIPTION": "Shows the current FPS.",
    "STARTUP_ARGS_TITLE": "Startup arguments",
    "STARTUP_ARGS_DESC": "Launch the game with command line arguments.\n(changes will take effect after relaunch).",
    "FAST_EXIT_TITLE": "Fast exit",
    "FAST_EXIT_DESC": "Quickly close this program.",
    "FAST_EXIT_HOTKEY_TITLE": "Key to exit",
    "FPS_TITLE": "FPS",
    "LANGUAGE_SELECT": "Select your language",
    "GodMode": "God Mode",
    "UltSkills": "Ult Skills",
    "UltStamina": "Ult Stamina",
    "HitMultiplier": "Hit Multiplier",
    "HitMultiplierDisc": "Hit Multiplier",
    "PlayerSpeed": "Player Speed",
    "AntiDither": "Anti Dither",
    "BigJump": "Big Jump",
    "Critical": "Critical",
    "ResonantChain": "Resonant Chain",
    "WalkOnWater": "Walk On Water",
    "Enabled": "Enabled",
    "AutoDodge": "AutoDodge",
    "AutoDodge_Disc": "AutoDodge",
    "ResonantChain_Disc": "ResonantChain ",
    "FontSize": "FontSize",
    "Range": "Range",
    "Text": "Text",
    "Show Name": "Show Name",
    "Show Line": "Show Line",
    "Show Distance": "Show Distance",
    "Show Class": "Show Class",
    "Show Type": "Show Type",
    "Show ALL": "Show ALL",
    "Type": "Type",
    "Animal": "Animal",
    "Treasure": "Treasure",
    "Collection": "Collection",
    "Crystal": "Crystal",
    "Gameplay": "Gameplay",
    "Monster": "Monster",
    "NPC": "NPC",
    "Vision": "Vision",
    "Tp": "Tp",
    "MapTp": "MapTp",
    "QuestTp": "QuestTp",
    "This software is still under testing and cannot guarantee complete security If you obtained it through purchase, then you have been scammed": "This software is still under testing and cannot guarantee complete security If you obtained it through purchase, then you have been scammed"
  },
  "CN": {
    "MODULE_ABOUT": "关于",
    "MODULE_PLAYER": "玩家",
    "MODULE_WORLD": "世界",
    "MODULE_VISUALS": "视觉",
    "MODULE_ESP": "透视",
    "MODULE_MISC": "其它",
    "MODULE_SETTINGS": "设置",
    "About": "关于",
    "Player": "玩家",
    "World": "世界",
    "Visuals": "视觉",
    "ESP": "透视",
    "MISC": "其它",
    "Settings": "设置",
    "Author": "主创:",
    "EchoTeam": "EchoTeam",
    "WWEcho is developing": "WWEcho 仍处于开发中",
    "SETTINGS_LANGUAGE": "语言设置",
    "SETTINGS_GENERAL": "通用",
    "MENU_HOTKEY_TITLE": "显示菜单",
    "CONSOLE_HOTKEY_TITLE": "显示控制台",
    "CONSOLE_HOTKEY_DESC": "开关控制台窗口",
    "SHOW_STATUS_WINDOW_TITLE": "显示功能状态窗口",
    "SHOW_STATUS_WINDOW_DESC": "创建一个窗口显示当前激活的功能",
    "MOVE_STATUS_TITLE": "可移动状态窗口",
    "SHOW_FPS_TITLE": "显示当前帧率",
    "SHOW_FPS_DESCRIPTION": "显示当前帧率",
    "STARTUP_ARGS_TITLE": "启动参数",
    "STARTUP_ARGS_DESC": "使用命令行参数启动游戏.\n（更改将在重新启动后生效）。",
    "FAST_EXIT_TITLE": "快速退出",
    "FAST_EXIT_DESC": "强制退出游戏.",
    "FAST_EXIT_HOTKEY_TITLE": "Key to exit",
    "FPS_TITLE": "FPS",
    "LANGUAGE_SELECT": "选择你的语言",
    "GodMode": "无敌模式",
    "UltSkills": "无限技能",
    "UltStamina": "无限体力",
    "HitMultiplier": "倍数攻击",
    "HitMultiplierDisc": "倍数攻击",
    "PlayerSpeed": "玩家速度",
    "AntiDither": "反虚化",
    "BigJump": "大跳",
    "Critical": "暴击率",
    "ResonantChain": "共鸣链",
    "WalkOnWater": "水上行走",
    "Enabled": "开/关",
    "AutoDodge": "自动闪避",
    "AutoDodge_Disc": "自动闪避",
    "ResonantChain_Disc": "共鸣链6",
    "FontSize": "字体大小",
    "Range": "半径",
    "Text": "文本",
    "Show Name": "显示名字",
    "Show Line": "显示线条",
    "Show Distance": "显示距离",
    "Show Class": "显示类名",
    "Show Type": "显示类型",
    "Show ALL": "显示所有",
    "Type": "类型",
    "Animal": "动物",
    "Treasure": "宝箱",
    "Collection": "收集品",
    "Crystal": "矿石破坏物",
    "Gameplay": "解谜玩法",
    "Monster": "怪物",
    "NPC": "NPC",
    "Vision": "声骸",
    "Tp": "传送",
    "MapTp": "地图传送",
    "QuestTp": "任务传送",
    "This software is still under testing and cannot guarantee complete security If you obtained it through purchase, then you have been scammed": "这个软件处于测试中,它是免费的,如果你是购买获得那你被骗了"
  }
})";
}
